# Generated by Django 2.0.4 on 2018-04-22 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('city', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='app.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('pincode', models.CharField(max_length=8)),
                ('street_address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('unique_id', models.CharField(max_length=256)),
                ('city', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='app.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
                ('available', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.ForeignKey(limit_choices_to={'available': 't'}, on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
        migrations.AddField(
            model_name='cities',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
    ]
