# Generated by Django 2.0.4 on 2018-04-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='unique_id',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField><django.db.models.fields.EmailField><django.db.models.fields.CharField>', max_length=100, unique=True),
        ),
    ]
