# Generated by Django 2.0.4 on 2018-04-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180419_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='unique_id',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
